// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220822103545_AddTransport")]
    partial class AddTransport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp1.Data.Entity.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LordDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransportTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlordDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transport");
                });

            modelBuilder.Entity("BlazorApp1.Data.Entity.TransportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("LordPointId")
                        .HasColumnType("int");

                    b.Property<int>("LordRT")
                        .HasColumnType("int");

                    b.Property<int>("UnlordPointId")
                        .HasColumnType("int");

                    b.Property<int>("UnlordRT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
